[package]
name = "oneliner"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Oneline Rust model inference library with pluggable execution backends"
documentation = "https://docs.rs/oneliner"

[lints]
workspace = true

[features]

default = ["iree-runtime"]
alloc = ["oneliner-runtime/alloc"] # Enable heap-allocation for "owned" model workspace.
iree-runtime = ["oneliner-runtime/iree-runtime"]

ariel-os = ["oneliner-runtime/ariel-os"] # Enable Ariel OS's threading support and multicore executor.

ndarray = ["oneliner-runtime/ndarray"]


[dependencies]
oneliner-macro.workspace = true
oneliner-runtime.workspace = true
