[package]
name = "OneLiner"
version = "0.1.0"
edition = "2021"
description = "One-line Rust model binding macro with pluggable backends"

[lib]
name = "OneLiner"

[features]
default = ["iree-runtime"]
alloc = []
iree-runtime = []
microflow-runtime = ["dep:microflow"]
ariel-os = ["dep:ariel-os", "ariel-os/threading", "dep:heapless"]
ndarray = ["dep:ndarray"]


[dependencies]
ndarray = { version = "0.17.2", default-features = false, optional = true }
microflow = { version = "=0.1.3", default-features = false, optional = true }
oneliner-macro = { path = "../oneliner-macro" }
ariel-os = { version = ">=0.4.0", optional = true, default-features = false }
critical-section = "1.2.0"
defmt = { version = "1.0.0" }
log = { version = "0.4.26"}
aligned ={ version = "0.4.3" }
portable-atomic = { version = "1", default-features = false }
heapless ={ version = "0.9.3", optional = true}
