[package]
name = "oneliner-runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Runtime support for Oneliner model inference"
documentation = "https://docs.rs/oneliner-runtime"

[lints]
workspace = true

[features]
default = ["iree-runtime"]
alloc = []
iree-runtime = []
ariel-os = ["dep:ariel-os", "dep:oneliner-ariel-os-executor"]
ndarray = ["dep:ndarray"]

[dependencies]
aligned.workspace = true
ariel-os = { workspace = true, optional = true }
critical-section.workspace = true
log.workspace = true
ndarray = { workspace = true, optional = true }
oneliner-ariel-os-executor = { workspace = true, optional = true, features = ["enabled"] }
oneliner-executor.workspace = true
oneliner-iree-abi.workspace = true
portable-atomic.workspace = true
