[package]
name = "oneliner-ariel-os-executor"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Ariel OS Multi-core executor for Oneliner"
documentation = "https://docs.rs/oneliner-ariel-os-executor"

[lints]
workspace = true

[features]
enabled = [] # Dummy feature to enable the executor implementation for Ariel OS and avoid cargo test failed. Must be enabled when using this crate.

[dependencies]
ariel-os.workspace = true
heapless.workspace = true
oneliner-executor.workspace = true
portable-atomic.workspace = true
